### ISSUE TITLE
Error Running python3 async_run-Error decoding

### ISSUE THREAD

**Issue by bbaileyga1** [obrigg/meraki-health-check#5]
I have two orgs, When running on 1st organization script completes without issues. When running on 2nd organization (much larger device count)
I get the following output with logging turned on:2023-08-17 20:22:54       meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'version': '1.36.0', 'api_key': '************************************498e', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'network_delete_retry_wait_time': 180, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': False, 'be_geo_id': None, 'caller': 'Healthcheck/22.12 OBrigg', 'use_iterator_for_get_pages': False}
2023-08-17 20:22:54       meraki:    DEBUG > {'tags': ['organizations', 'configure'], 'operation': 'getOrganizations', 'method': 'GET', 'url': '/organizations', 'params': None}
2023-08-17 20:22:54       meraki:     INFO > GET https://api.meraki.com/api/v1/organizations
2023-08-17 20:22:55       meraki:     INFO > organizations, getOrganizations - 200 OK
2023-08-17 20:22:58       meraki:    DEBUG > {'tags': ['organizations', 'configure', 'networks'], 'operation': 'getOrganizationNetworks', 'page': 1}
2023-08-17 20:22:58       meraki:     INFO > GET https://api.meraki.com/api/v1/organizations/613052499275809599/networks
2023-08-17 20:22:58       meraki:     INFO > organizations, getOrganizationNetworks; page 1 - 200 OK
[meraki_api__log__2023-08-17_20-22-54.log](https://github.com/obrigg/meraki-health-check/files/12374319/meraki_api__log__2023-08-17_20-22-54.log)

**Comment by obrigg** [comment]
Thanks for opening a separate issue. 
What error did you get this time? It looks like the log stopped at getting the list of networks in the organization.

**Comment by bbaileyga1** [comment]
Kindly select the organization ID you would like to query: 0
2023-08-18 09:48:59   meraki.aio:     INFO > Meraki dashboard API session initialized with these parameters: {'version': '1.36.0', 'api_key': '************************************498e', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 2, 'action_batch_retry_wait_time': 60, 'network_delete_retry_wait_time': 180, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 100, 'simulate': False, 'be_geo_id': None, 'caller': 'Healthcheck/22.12 OBrigg', 'use_iterator_for_get_pages': False, 'maximum_concurrent_requests': 5, 'version_warning_string': 'This library requires Python 3.7 at minimum. Python versions 3.6 and below are end of life and end of support per the Python maintainers, and your interpreter version details are: \nplatform.python_version_tuple()[0] = 3\nplatform.python_version_tuple()[1] = 11\nplatform.python_version is 3.11.4\nPlease consult the readme at your convenience: https://github.com/meraki/dashboard-api-python'}
2023-08-18 09:49:00   meraki.aio:     INFO > GET https://api.meraki.com/api/v1/organizations/613052499275809599/admins
2023-08-18 09:49:00   meraki.aio:     INFO > organizations, getOrganizationAdmins > https://api.meraki.com/api/v1/organizations/613052499275809599/admins - 200 OK
Admin Arthur Sellers (email: asellers@protossecurity.com) has 2FA enabled
Admin RSM Network Solution Set (email: networksolutionset@rsmus.com) has 2FA enabled
More than one admin has full rights. This is recommended.
2023-08-18 09:49:00   meraki.aio:     INFO > GET https://api.meraki.com/api/v1/organizations/613052499275809599/apiRequests
2023-08-18 09:49:00   meraki.aio:     INFO > GET https://api.meraki.com/api/v1/organizations/613052499275809599/apiRequests
2023-08-18 09:49:01   meraki.aio:     INFO > organizations, getOrganizationApiRequests; page 1 > https://api.meraki.com/api/v1/organizations/613052499275809599/apiRequests - 200 OK
2023-08-18 09:49:02   meraki.aio:     INFO > organizations, getOrganizationApiRequests; page 1 > https://api.meraki.com/api/v1/organizations/613052499275809599/apiRequests - 200 OK
Some other ERROR: 'URL' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/baileb/meraki-health-check/meraki-health-check/async_run.py", line 1386, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/baileb/meraki-health-check/meraki-health-check/async_run.py", line 1259, in main
    await async_check_org_admins(aiomeraki)
  File "/home/baileb/meraki-health-check/meraki-health-check/async_run.py", line 683, in async_check_org_admins
    await task
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/baileb/meraki-health-check/meraki-health-check/async_run.py", line 706, in async_check_api_calls
    for request in api_requests:
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'api_requests' where it is not associated with a value
[meraki_api__log__2023-08-18_09-47-18.log](https://github.com/obrigg/meraki-health-check/files/12380033/meraki_api__log__2023-08-18_09-47-18.log)

**Comment by obrigg** [comment]
This looks like a bug in the Meraki Python SDK at version 1.36.0. Running the script with version 1.34.0 works fine.
I created [an issue](https://github.com/meraki/dashboard-api-python/issues/222) for further investigation.

**Comment by obrigg** [comment]
Looks like the issue with the SDK was resolved.
Can you kindly update the SDK (`pip install meraki==1.37.2`) and try running the script again?

**Comment by obrigg** [comment]
closing due to inactivity.
