### ISSUE TITLE
Error during executed

### ISSUE THREAD

**Issue by well-souza** [obrigg/meraki-health-check#6]
Traceback (most recent call last):
  File "async_run.py", line 1386, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "async_run.py", line 1339, in main
    check_wireless_ports(networks)
  File "async_run.py", line 745, in check_wireless_ports
    if ap["serial"] in results[network_name]["channel_utilization_check"].keys():
KeyError: 'N/A'

**Comment by obrigg** [comment]
Thanks to JPYDX (https://github.com/obrigg/meraki-health-check/issues/8), we may have a lead on this.
Can you kindly add a print statement for the AP?

```
    for ap in aggregated_ap_uplinks:
        print(ap)
        # Translating network ID to network name
        network_id = ap['network']['id']
        network_name = "N/A"
        for network in networks:
            if network['id'] == network_id:
                network_name = network['name']
                break
```

I'd like to see which AP cause the script to break, and whether there's a problem with it's Network ID.

**Comment by obrigg** [comment]
Closing due to inactivity.
